### ISSUE TITLE
Comments with target browsers

### ISSUE THREAD

**Issue by vladimirschneider** [browserslist/browserslist#567]
Hi,

I think about special comments with target browsers to compare with browserslist and remove css section if combiner sees fit to do it.

For example:

```css
/** browserslist
IE 10, Chrome < 30
*/
template {
  display: none;
}
```

This can be use plugins with css for old browsers and make css bundles size lesses.
